#!/usr/bin/env python3
"""
Simple test runner for DeepAgents CLI.

Usage:
    python scaffold/runner.py <agent_name> <prompt> [--output-dir <dir>]

Example:
    python scaffold/runner.py langchain_agent "Create a SQL agent" --output-dir test_results
"""

import sys
import argparse
from pathlib import Path
import pexpect
from io import StringIO


def run_deepagents_test(agent_name: str, prompt: str, output_dir: Path, working_dir: Path):
    """Run a DeepAgents test and generate reports."""

    print(f"\n{'='*70}")
    print(f"Testing DeepAgents: {agent_name}")
    print(f"{'='*70}\n")

    # Add summary request to prompt
    summary_file = working_dir / "agent_summary.txt"
    enhanced_prompt = f"""{prompt}

After completing the task, write a comprehensive summary to {summary_file} that includes:
- What you did
- Skills you consulted
- Key decisions made
- All code you generated (with full code blocks)
- Any files you created
- Final status

Format the summary clearly for human review."""

    print(f"Prompt: {prompt}\n")
    print("Running agent (this may take 30-120 seconds)...")

    # Find deepagents
    deepagents_path = working_dir / ".venv" / "bin" / "deepagents"
    if not deepagents_path.exists():
        print(f"Error: deepagents not found at {deepagents_path}")
        sys.exit(1)

    # Run with -m flag using enhanced prompt
    cmd = f"{deepagents_path} --agent {agent_name} --auto-approve -m {repr(enhanced_prompt)}"

    output_buffer = StringIO()
    process = pexpect.spawn(
        "/bin/zsh",
        ["-c", cmd],
        cwd=str(working_dir),
        timeout=300,
        encoding='utf-8',
        echo=False
    )
    process.logfile_read = output_buffer

    try:
        process.expect(pexpect.EOF, timeout=120)
    except pexpect.TIMEOUT:
        print("Warning: Timeout - agent may still be running")

    process.close()

    # Check if agent wrote summary file
    output_dir.mkdir(parents=True, exist_ok=True)
    if summary_file.exists():
        # Use agent-written summary
        agent_summary_content = summary_file.read_text()
        (output_dir / "summary.txt").write_text(agent_summary_content)
        print("\n✓ Agent wrote summary")
    else:
        # Agent didn't write summary
        print("\n⚠ Agent did not write summary file")
        (output_dir / "summary.txt").write_text("No summary generated by agent")

    print(f"\n{'='*70}")
    print(f"Session complete")
    print(f"{'='*70}\n")
    print(f"Review output:\n  {output_dir / 'summary.txt'}")

    return 0


def main():
    parser = argparse.ArgumentParser(description="Test DeepAgents CLI")
    parser.add_argument("agent", help="Agent name (e.g., langchain_agent)")
    parser.add_argument("prompt", help="Prompt to test")
    parser.add_argument("--output-dir", help="Output directory (default: logs/<timestamp>)")
    parser.add_argument("--working-dir", default=".", help="Working directory")

    args = parser.parse_args()

    # Default to logs directory with timestamp
    if args.output_dir:
        output_dir = Path(args.output_dir)
    else:
        from datetime import datetime
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        skills_dir = Path(__file__).parent.parent
        output_dir = skills_dir / "logs" / f"{args.agent}_{timestamp}"

    working_dir = Path(args.working_dir).resolve()

    return run_deepagents_test(args.agent, args.prompt, output_dir, working_dir)


if __name__ == "__main__":
    sys.exit(main())
